jobs: 10
jobname: "{rule}.{jobid}"
cluster: "sbatch -t {resources.maxtime} --mem={resources.mem_mb} -c {threads} --output=slurm_logs/log_{rule}_%j.log --mail-type=FAIL"
default-resources: [mem_mb=4000, maxtime="1:00:00"]
max-jobs-per-second: 5
max-status-checks-per-second: 20
restart-times: 5
rerun-incomplete: True
latency-wait: 60
